### ISSUE TITLE
First issue

### ISSUE THREAD

**Issue by mcornella** [ohmyzsh/do-not-use#1]
This should be answered with a comment from @ohmyzsh-bot

EDIT: trigger issues.edited event
EDIT 2: trigger another event

**Comment by mcornella** [comment]
```
13:27:35.725Z ERROR probot: signature does not match event payload and secret
  Error: signature does not match event payload and secret
      at verifyAndReceive (/home/marc/code/ohmyzsh/ohmyzsh-bot/node_modules/@octokit/webhooks/middleware/verify-and-receive.js:9:19)
      at getPayload.then (/home/marc/code/ohmyzsh/ohmyzsh-bot/node_modules/@octokit/webhooks/middleware/middleware.js:46:14)
      at processTicksAndRejections (internal/process/task_queues.js:86:5)
13:27:35.736Z  INFO http: POST / 400 - 16.63 ms (id=8b0e2444-f285-494d-b0cb-5d4dc1115917)
13:27:35.743Z ERROR probot: Bad Request
  Error: Bad Request
      at Request.callback (/home/marc/code/ohmyzsh/ohmyzsh-bot/node_modules/superagent/lib/node/index.js:706:15)
      at IncomingMessage.parser (/home/marc/code/ohmyzsh/ohmyzsh-bot/node_modules/superagent/lib/node/index.js:916:18)
      at IncomingMessage.emit (events.js:198:15)
      at IncomingMessage.EventEmitter.emit (domain.js:481:20)
      at endReadableNT (_stream_readable.js:1139:12)
      at processTicksAndRejections (internal/process/task_queues.js:81:17)
```

**Comment by mcornella** [comment]
@ohmyzsh-bot
